-- Sierra Circuits replication: Snowflake objects for the Data Cloud connector.
-- Run as ACCOUNTADMIN (or a role with CREATE DATABASE / CREATE ROLE / CREATE USER).
-- Replace <PUBLIC_KEY_BODY> with the contents of rsa_key.pub, header/footer lines removed,
-- joined into one line. See README.md for the openssl commands.

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS SIERRA_WH
  WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS SIERRA_REPLICA;
CREATE SCHEMA IF NOT EXISTS SIERRA_REPLICA.CRM;

-- Least-privilege role for Data Cloud. Read-only.
CREATE ROLE IF NOT EXISTS DATACLOUD_READER;
GRANT USAGE ON WAREHOUSE SIERRA_WH TO ROLE DATACLOUD_READER;
GRANT USAGE ON DATABASE SIERRA_REPLICA TO ROLE DATACLOUD_READER;
GRANT USAGE ON SCHEMA SIERRA_REPLICA.CRM TO ROLE DATACLOUD_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA SIERRA_REPLICA.CRM TO ROLE DATACLOUD_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SIERRA_REPLICA.CRM TO ROLE DATACLOUD_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA SIERRA_REPLICA.CRM TO ROLE DATACLOUD_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SIERRA_REPLICA.CRM TO ROLE DATACLOUD_READER;

-- Service user for the connector. Key-pair auth, no password.
CREATE USER IF NOT EXISTS DATACLOUD_SVC
  DEFAULT_ROLE = DATACLOUD_READER
  DEFAULT_WAREHOUSE = SIERRA_WH
  DEFAULT_NAMESPACE = SIERRA_REPLICA.CRM
  TYPE = SERVICE
  RSA_PUBLIC_KEY = '<PUBLIC_KEY_BODY>';
GRANT ROLE DATACLOUD_READER TO USER DATACLOUD_SVC;

-- Verify the key landed.
DESC USER DATACLOUD_SVC;
